name:                glm-haskell
version:             0.1.0.0
github:              "adamConnerSax/glm-haskell"
license:             BSD3
author:              "Adam Conner-Sax"
maintainer:          "adam_conner_sax@yahoo.com"
copyright:           "2019 Adam Conner-Sax"

extra-source-files:
- Readme.md
- ChangeLog.md

synopsis:            estimate generalized linear models
category:            Numeric

description:         Please see the README on GitHub at <https://github.com/adamConnerSax/glm-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5.0.0 && < 0.7
- exceptions >= 0.10.0 && < 0.11
- foldl >= 1.4.0 && <= 1.5
- hmatrix >= 0.20.0 && < 0.21
- hmatrix-nlopt >= 0.1.2 && < 0.2
- nonlinear-optimization >= 0.3.11 && < 0.4
- nonlinear-optimization-ad >= 0.2 && < 0.3
- polysemy >= 0.7.0 && < 0.8
- polysemy-zoo >= 0.3.0 && < 0.5
- polysemy-plugin >= 0.2.2 && < 0.3
- sparse-linear-algebra >= 0.3 && < 0.4
- statistics >= 0.15.0 && < 0.16
- text >= 1.1.0.1 && < 1.3
- vector >= 0.11.0.0 && < 0.13

flags:
  dump-core:
    description: Dump HTML for the core generated by GHC during compilation
    default:     False
    manual:      True

library:
  ghc-options: -O -Wall -fplugin=Polysemy.Plugin
  source-dirs: src

  when:
    - condition: flag(dump-core)
      dependencies:
        - dump-core
      ghc-options:
        - -fplugin=DumpCore
        - -fplugin-opt DumpCore:core-html

